#:kivy 2.0.0

<GameScreen>:
    
    FloatLayout:
        pos: 0, 0
        size: root.width, root.height
        
        GridLayout:
            cols: 2
            pos_hint: {'x': 0.3, 'y': 0.3}
            size_hint: None, None
            size: root.width*0.4, root.height*0.4

            Button:
                text: "1"
            Button:
                text: "2"
            Button:
                text: "3"
            Button:
                text: "4"
            

